### ISSUE TITLE
Export: checksum of data

### ISSUE THREAD

**Issue by jmlich** [rh-lab-q/conflab#20]
The /export/conference_list/ should contain checksum of data for each conference. The value should correspond with /<url_id>/export/m_app/ value.

For example the item if16 should have checksum from http://python-conflab.rhcloud.com/if16/export/m_app/ json.

I made a placeholder for it 
2719f0516e0c576d2f926270fc155ba5f47aa7f6

**Comment by jmlich** [comment]
My current implementation relies on the same value in both exports

**Comment by pkubatrh** [comment]
This will probably need some changes in the export itself. Created an issue for this - #23
