### ISSUE TITLE
poradi mistnosti by melo byt stejne pri editaci i pri zobrazeni

### ISSUE THREAD

**Issue by jmlich** [rh-lab-q/conflab#30]
SSIA

**Comment by pkubatrh** [comment]
V gitu opravene commitem ff935129df140b20b2a13520842612373641b064, jen to jeste neni pushle do openshiftu kvuli zmenam v planovaci, ktery jeste neni uplne stabilni.

**Comment by jmlich** [comment]
ok. Diky za info. Myslel jsem si, ze se na to zapomelo ..
