### ISSUE TITLE
logo

### ISSUE THREAD

**Issue by jmlich** [rh-lab-q/conflab#31]
stando, jak to vypada s logem?

**Comment by stlaz** [comment]
logo je zřejmě stále ve výrobě, kontaktuji grafičku pro více detailů

**Comment by jmlich** [comment]
Přikládam sketche od grafičky.
![confla_sketch](https://cloud.githubusercontent.com/assets/6171637/14522638/ce40aa50-022f-11e6-82a2-85b359fb30b2.png)

**Comment by pkubatrh** [comment]
Dalsi sketche
![confla_sketch2](https://cloud.githubusercontent.com/assets/5138065/14845272/6c026594-0c5d-11e6-8ab9-5c28ae331ab3.png)

**Comment by stlaz** [comment]
Meeting minutes:
Z první části se líbí hlavně plochá loga, C s o uvnitř,  hranaté Co a (Conf)la. Dál z druhé části je zajímavý nápad program s lopatkou a případně by bylo možné využít puzzle s kalendářem.
